flask_mark_style/app/blueprints/courses/__init__.py
from flask import Blueprint

bp = Blueprint('courses', __name__)

from . import routes

flask_mark_style/app/blueprints/courses/routes.py
from flask import render_template
from flask_login import login_required, current_user
from . import bp
from app.models import Course, Lesson


@bp.route('/')
def index():
    courses = Course.query.all()
    return render_template('courses/index.html', courses=courses)


@bp.route('/<slug>')
def detail(slug):
    course = Course.query.filter_by(slug=slug).first_or_404()
    return render_template('courses/detail.html', course=course)


@bp.route('/<slug>/lesson/<lesson_slug>')
@login_required
def lesson(slug, lesson_slug):
    lesson = Lesson.query.join(Course).filter(Course.slug == slug, Lesson.slug == lesson_slug).first_or_404()
    return render_template('courses/lesson.html', lesson=lesson)

flask_mark_style/templates/courses/detail.html
{% extends '_base.html' %}
{% block title %}{{ course.title }}{% endblock %}
{% block content %}
<h1>{{ course.title }}</h1>
<p>{{ course.description_md }}</p>
<ul>
  {% for lesson in course.lessons %}
  <li><a href="{{ url_for('courses.lesson', slug=course.slug, lesson_slug=lesson.slug) }}">{{ lesson.title }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

flask_mark_style/templates/courses/index.html
{% extends '_base.html' %}
{% block title %}Courses{% endblock %}
{% block content %}
<h1>Courses</h1>
<ul>
  {% for course in courses %}
  <li><a href="{{ url_for('courses.detail', slug=course.slug) }}">{{ course.title }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

flask_mark_style/templates/courses/lesson.html
{% extends '_base.html' %}
{% block title %}{{ lesson.title }}{% endblock %}
{% block content %}
<h1>{{ lesson.title }}</h1>
<p>{{ lesson.body_md }}</p>
{% endblock %}