flask_mark_style/app/blueprints/articles/__init__.py
from flask import Blueprint

bp = Blueprint('articles', __name__)

from . import routes

flask_mark_style/app/blueprints/articles/routes.py
from flask import render_template, request
from . import bp
from app.models import Article

@bp.route('/')
def index():
    articles = Article.query.order_by(Article.published_at.desc()).all()
    return render_template('articles/index.html', articles=articles)

@bp.route('/search')
def search():
    q = request.args.get('q','')
    results = []
    return render_template('articles/search.html', results=results, query=q)

@bp.route('/<slug>')
def detail(slug):
    article = Article.query.filter_by(slug=slug).first_or_404()
    return render_template('articles/detail.html', article=article)

flask_mark_style/app/search/__init__.py
from .indexer import SearchIndexer

search_indexer = SearchIndexer('instance/search')

flask_mark_style/templates/articles/detail.html
{% extends '_base.html' %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %}
<h1>{{ article.title }}</h1>
<p>{{ article.body_md }}</p>
{% endblock %}

flask_mark_style/templates/articles/index.html
{% extends '_base.html' %}
{% block title %}Articles{% endblock %}
{% block content %}
<h1>Articles</h1>
<ul>
  {% for a in articles %}
  <li><a href="{{ url_for('articles.detail', slug=a.slug) }}">{{ a.title }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

flask_mark_style/templates/articles/search.html
{% extends '_base.html' %}
{% block title %}Search{% endblock %}
{% block content %}<h1>Search</h1>{% endblock %}

flask_mark_style/templates/articles/topic.html
{% extends '_base.html' %}
{% block title %}Topic{% endblock %}
{% block content %}<h1>Topic</h1>{% endblock %}

flask_mark_style/templates/articles/year.html
{% extends '_base.html' %}
{% block title %}Year{% endblock %}
{% block content %}<h1>Year</h1>{% endblock %}