flask_mark_style/app/blueprints/newsletter/__init__.py
from flask import Blueprint

bp = Blueprint('newsletter', __name__)

from . import routes

flask_mark_style/app/blueprints/newsletter/routes.py
from flask import render_template, request, redirect, url_for, flash
from . import bp
from app.models import NewsletterIssue
from app.emails import email_adapter


@bp.route('/')
def archive():
    issues = NewsletterIssue.query.order_by(NewsletterIssue.sent_at.desc()).all()
    return render_template('newsletter/archive.html', issues=issues)


@bp.route('/<slug>')
def issue(slug):
    issue = NewsletterIssue.query.filter_by(slug=slug).first_or_404()
    return render_template('newsletter/issue.html', issue=issue)


@bp.route('/subscribe', methods=['GET', 'POST'])
def subscribe():
    if request.method == 'POST':
        email = request.form['email']
        token = 'sample-token'
        email_adapter.send_double_opt_in(email, token)
        flash('Check your email to confirm subscription.')
        return redirect(url_for('newsletter.archive'))
    return render_template('newsletter/subscribe.html')


@bp.route('/confirm')
def confirm():
    flash('Subscription confirmed.')
    return redirect(url_for('newsletter.archive'))

flask_mark_style/templates/newsletter/archive.html
{% extends '_base.html' %}
{% block title %}Archive{% endblock %}
{% block content %}
<h1>Newsletter Archive</h1>
<ul>
  {% for issue in issues %}
  <li><a href="{{ url_for('newsletter.issue', slug=issue.slug) }}">{{ issue.title }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

flask_mark_style/templates/newsletter/confirm.html
{% extends '_base.html' %}
{% block title %}Confirm{% endblock %}
{% block content %}<h1>Confirmed</h1>{% endblock %}

flask_mark_style/templates/newsletter/issue.html
{% extends '_base.html' %}
{% block title %}{{ issue.title }}{% endblock %}
{% block content %}
<h1>{{ issue.title }}</h1>
<p>{{ issue.body_md }}</p>
{% endblock %}

flask_mark_style/templates/newsletter/subscribe.html
{% extends '_base.html' %}
{% block title %}Subscribe{% endblock %}
{% block content %}
<h1>Subscribe</h1>
<form method="post">
  <input type="email" name="email">
  <button type="submit">Subscribe</button>
</form>
{% endblock %}